export const ACTIVITY_TYPE = {
  INVITATION_TO_WORKSPACE: 'INVITATION_TO_WORKSPACE',
  UPDATE_AN_WORKSPACE: 'UPDATE_AN_WORKSPACE',
  CREATE_AN_ACCOUNT: 'CREATE_AN_ACCOUNT',
  UPDATE_AN_ACCOUNT: 'UPDATE_AN_ACCOUNT',
  SHARE_AN_ACCOUNT: 'SHARE_AN_ACCOUNT',
  DELETE_AN_ACCOUNT: 'DELETE_AN_ACCOUNT',
  MEMBER_SHARE_AN_ACCOUNT: 'MEMBER_SHARE_AN_ACCOUNT',
  MEMBER_SHARE_A_WORKSPACE: 'MEMBER_SHARE_A_WORKSPACE'
}
