export const ENVIRONMENT_KEYS = {
  VITE_API_URL: import.meta.env.VITE_API_URL,
  VITE_SOCKET_URL: import.meta.env.VITE_SOCKET_URL,
  VITE_CLIENT_URL: import.meta.env.VITE_CLIENT_URL,
  VITE_EXTENSION_URL: import.meta.env.VITE_EXTENSION_URL,
  VITE_CLOUD_NAME: import.meta.env.VITE_CLOUD_NAME,
  VITE_UPLOAD_ASSETS_NAME: import.meta.env.VITE_UPLOAD_ASSETS_NAME,
  VITE_CLOUDINARY_UPLOAD_URL: import.meta.env.VITE_CLOUDINARY_UPLOAD_URL,
  VITE_CAPTCHAR_SITE_KEY: import.meta.env.VITE_CAPTCHAR_SITE_KEY,
  VITE_OPEN_STREET_MAP_API_URL: import.meta.env.VITE_OPEN_STREET_MAP_API_URL,
  VITE_ENCRYPTION_KEY: import.meta.env.VITE_ENCRYPTION_KEY,
  VITE_ENCRYPTION_IV: import.meta.env.VITE_ENCRYPTION_IV
}
