export const PATH = {
  HOME: '/',
  PROFILE: '/profile',
  LOGIN: '/login',
  REGISTER: '/register',
  CONFIRM_EMAIL: '/confirm-email/:id',
  FORGOT_PASSWORD: '/forgot-password',
  ADMIN_LOGIN: '/admin/login',
  ADMIN: '/admin',
  ADMIN_USERS: '/admin/users',
  ADMIN_PROFILE: '/admin/profile',
  VAULT: '/vault',
  VAULT_ACCOUNTS: '/vault/accounts',
  VAULT_CONTACT_INFOS: '/vault/contact-infos',
  VAULT_WORKSPACES: '/vault/workspaces',
  VAULT_WORKSPACE_DETAIL: '/vault/workspaces/:workspaceId',
  VAULT_LOGIN_HISTORY: '/vault/login-history',
  VAULT_TRASH: '/vault/trash',
  VAULT_PROFILE: '/vault/profile',
  VAULT_SETTINGS: '/vault/settings',
  CONFIRM_ACCOUNT_INVITATION: '/confirm-account-invitation/:inviteId',
  CONFIRM_WORKSPACE_INVITATION: '/confirm-workspace-invitation/:inviteId',
  TWO_FA_SUGGESTION: '/two-fa-recommendation',
  LOGIN_HISTORY_MAP: '/login-history-map',
  VERIFY_PAYMENT: '/verify-payment',
  NOT_FOUND: '*'
} as const
